### ISSUE TITLE
[BUG]:刷新推荐/页面的时候，发现会不停请求https://data.bilibili.com/log/web

### ISSUE THREAD

**Issue by finch0799** [magicdawn/Bilibili-Gate#138]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

刷新页面的时候，会不停请求https://data.bilibili.com/log/web这个地址，取其中一个请求如下，能看到有什么error描述
https://data.bilibili.com/log/web?00220317324563916512024-11-24T13:53:11.651Z|ERROR|main.frontend.bilibili-log-report-seed|runtime|1|Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/131.0.0.0%20Safari/537.36|https://www.bilibili.com/|https://www.bilibili.com/video/BV1RNGDeREsC/|{%22url%22:%22chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=%25E8%25B7%259F%25E8%25B8%25AA%25E9%2593%25BE%25E6%258E%25A5%25E5%2587%2580%25E5%258C%2596.user.js&id=6e160998-28ce-43fa-922c-19e6b8053ab7%22,%22pageUrl%22:%22https://www.bilibili.com/%22,%22line%22:863,%22col%22:53,%22errorMsg%22:%22TypeError:%20Cannot%20read%20properties%20of%20null%20(reading%20%27includes%27)\n%20%20%20%20at%20Proxy.%3Canonymous%3E%20(chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=%25E8%25B7%259F%25E8%25B8%25AA%25E9%2593%25BE%25E6%258E%25A5%25E5%2587%2580%25E5%258C%2596.user.js&id=6e160998-28ce-43fa-922c-19e6b8053ab7:863:53)\n%20%20%20%20at%20Pt%20(%3Canonymous%3E:10:89)\n%20%20%20%20at%20t.%3Ccomputed%3E%20(%3Canonymous%3E:77:280)\n%20%20%20%20at%20Pt%20(%3Canonymous%3E:10:89)\n%20%20%20%20at%20r%20(%3Canonymous%3E:32:484)\n%20%20%20%20at%20%3Canonymous%3E:33:112\n%20%20%20%20at%20%3Canonymous%3E:22:300\n%20%20%20%20at%20_%20(%3Canonymous%3E:22:319)%22}

![QQ截图20241124215925](https://github.com/user-attachments/assets/2ce1ffb2-b54b-497b-a26a-05a903dfa1f3)

这个也导致了列表刷新出来的速度很慢。

### 预期结果

不一直请求接口，恢复正常刷新速度

**Comment by magicdawn** [comment]
B站自己的...反馈给B站让他们不要收集用户 log 了

至于怎么反馈, 我也不知道, 你要是知道了, 可以告诉我一下...

**Comment by magicdawn** [comment]
安装 uBlock Origin 插件的默认规则可以阻止这个请求, 我以为这类插件都大家都标配了

**Comment by finch0799** [comment]
好的，谢谢你
