### ISSUE TITLE
[BUG]: 用户名和日期字体颜色不再是灰色（--ant-color-link 未定义）

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/Bilibili-Gate#141]
### 环境

浏览器: Chrome
浏览器版本: 131.0.6778.86
脚本管理器: TamperMonkey
脚本版本: 0.29.2

### 问题详细描述

0.29.0及以前的版本，用户名和日期字体颜色是灰色，跟标题颜色区分开。

0.29.1增加了
```
.bilibili-gate-root a:where(:not(.ant-btn)) {
    color: var(--ant-color-link);
}
.bilibili-gate-root a:where(:not(.ant-btn)):visited {
    color: var(--ant-color-link);
}
```
但是 `--ant-color-link` 未定义
![屏幕截图 2024-12-02 140411](https://github.com/user-attachments/assets/26467ada-d3ec-4f2e-9058-a3d204985e5a)
结果用户名和日期字体字体颜色变成跟标题一样了。关掉这个样式可以恢复原来的样子

### 预期结果

用户名和日期字体颜色保留原来的淡灰色

**Comment by magicdawn** [comment]
sorry 我没注意到这个变化

**Comment by magicdawn** [comment]
感谢报告此问题, fixed in v0.29.3
