### ISSUE TITLE
[BUG]:视频卡片遮挡下拉选项

### ISSUE THREAD

**Issue by River-2024** [magicdawn/Bilibili-Gate#142]
### 环境

浏览器: Chrome
浏览器版本: 131.0.6778.140
脚本管理器: TamperMonkey
脚本版本: 0.3.0

### 问题详细描述

鼠标置于「动态-全部」选项上，选项会被视频卡片遮挡，问题同样出现在「收藏-全部」选项上
![QQ20241219-093339](https://github.com/user-attachments/assets/b7f73fdd-5618-4453-9a13-bc20c70525b7)

**Comment by magicdawn** [comment]
1. Chrome 未复现
2. 可能与 282b9fc 有关 (0.30.2 已包含)
