### ISSUE TITLE
[FEAT]: 弹窗/浮动模式没了吗？

### ISSUE THREAD

**Issue by jhdxr** [magicdawn/Bilibili-Gate#144]
### 环境

浏览器: Firefox
浏览器版本: 133.0.3
脚本管理器: 暴力猴
脚本版本: 2.29.0

### 问题详细描述

之前的版本有个按钮可以单独开启一个浮窗的，现在这个功能是没了吗？

**Comment by magicdawn** [comment]
【查看更多】已于近期移除

移除理由
1. 与【全屏模式】功能重复
2. 该功能存在于分区首页时期, 目的是为了查看首页各种分区, 查看更多以弹窗形式存在. 现在默认首页已改为推荐流, 无其他东西可看. 需要查看自带首页推荐可禁用本脚本即可.

---

移除版本 https://github.com/magicdawn/Bilibili-Gate/releases/tag/v0.30.3
非要用可以固定版本到 v0.30.2

---
复制自 https://greasyfork.org/zh-CN/scripts/443530-bilibili-gate/discussions/272239#comment-554491

**Comment by yinzhefuyun** [comment]
可是我是用这个脚本看【动态】tab，这个页面下查看更多很有必要，因为刷新在99.99%的情况下是不会刷新出新内容，
而查看更多可以看到早于最新10个视频的其他up主发布的视频，而不是通过右上角的动态（那个动态在50个动态视频后只能点击查看全部动态来查看更早的更新，而且不能预览视频）
我只想在B站首页看完我关注的UP发的视频，任何点开【推荐】栏目再看其他视频，
【查看更多】功能的删除导致了【动态】tab处于非【全屏模式】下基本不用

**Comment by magicdawn** [comment]
remove commit 45436cb
revert commit 430508c
已 revert
